### ISSUE TITLE
Adding maintainers / contributors

### ISSUE THREAD

**Issue by samueleresca** [samueleresca/pekko-quartz-scheduler#45]
Currently I'm the only maintainer for this project. Even though my plan is to keep maintaining the project, I would like to avoid to be the single point of failure. 

The maintaining activities involve:
- Merging dependencies bumps from scala steward.
- Doing periodic releases (at the moment the release process is manual see: https://github.com/samueleresca/pekko-quartz-scheduler/blob/main/RELEASE.md)
- Minor fixes and improvements.
- Supporting new scala versions.

**Comment by samueleresca** [comment]
@mdedetrich See the issue description. Are you interested in being a contributor? Please let me know. As mentioned, I'm still planning to maintain the project, but I would remove myself as a single point of failure.

**Comment by mdedetrich** [comment]
> @mdedetrich See the issue description. Are you interested in being a contributor? Please let me know. As mentioned, I'm still planning to maintain the project, but I would remove myself as a single point of failure.

Yes I am interested

Ar some point I wanted to raise including this into Apache Pekko proper but now is not the best time for that so for now this is appropriate

**Comment by samueleresca** [comment]
@mdedetrich, I'm proceeding by adding you as a collaborator of the repo. On top of that I will review the release process because currently is manual.

Regarding including the code in Apache Pekko, I support the decision. The repo provide an enachement to Apache Pekko and it is tightly coupled with that anyway. On top of that, It don't think it will add much overhead to the project.

**Comment by mdedetrich** [comment]
> Regarding including the code in Apache Pekko, I support the decision. The repo provide an enachement to Apache Pekko and it is tightly coupled with that anyway. On top of that, It don't think it will add much overhead to the project.

Agreed, lets explore this after TLP graduation!

**Comment by mdedetrich** [comment]
Shall we close this as done?
