### ISSUE TITLE
Release latest version of the library that is compiled with the latest versions of pekko-actor libraries

### ISSUE THREAD

**Issue by seveneves** [samueleresca/pekko-quartz-scheduler#58]
Latest version `1.2.0-pekko-1.0.x` of the library is using `1.0.1` version of pekko-actor and this breaks strict schema eviction rules we are using for all pekko libraries. 

Would it be possible to release a new version of this lib that is compiled with the latest `pekko-actor `, ie `1.0.2`?

We are currently solving this problem with `.excludeAll(ExclusionRule(organization = "org.apache.pekko"))` and re-adding the transitive dependencies manually but this is not an optimal solution.

**Comment by samueleresca** [comment]
Hi @seveneves,

> Would it be possible to release a new version of this lib that is compiled with the latest pekko-actor , ie 1.0.2?

yes, I will proceed by updating the pekko version to the latest and publish in the next couple of days

**Comment by samueleresca** [comment]
`1.2.1-pekko-1.0.x` is out with the latest pekko
