### ISSUE TITLE
Revert from Scala 3.4 to Scala 3.3

### ISSUE THREAD

**Issue by gbarmashiahflir** [samueleresca/pekko-quartz-scheduler#72]
As a library, it is recommended to use Scala LTS version which is the 3.3.x line. (currently 3.3.3)
The current version of this lib is 3.4.x which means that any project using the 3.3 LTS version of Scala, can't use this library.
See more details here:
https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html
https://virtuslab.com/blog/technology/the-scala-3-compatibility-story/
https://scala-lang.org/blog/2023/05/30/scala-3.3.0-released.html

**Comment by samueleresca** [comment]
Thanks @gbarmashiahflir for pointing it out. I'm about to release a new version that relies on the Scala LTS version.
