### ISSUE TITLE
README says that it supports 2.13.x instead of 3.x

### ISSUE THREAD

**Issue by LewisMitchell** [samueleresca/pekko-quartz-scheduler#86]
The README says that this library supports 2.13.x (which I assume is meant as the latest Scala version), whereas now it supports Scala 3 also.

Plus the latest Pekko (in build.sbt) is now 1.1.x

I've made a PR with the changes if you agree 😄 :
https://github.com/samueleresca/pekko-quartz-scheduler/pull/85

**Comment by mayur9991** [comment]
@samueleresca Is there any plan to release a new version with Pekko 1.1.x ?

**Comment by samueleresca** [comment]
@LewisMitchell you PR is merged.

**Comment by samueleresca** [comment]
@mayur9991 I have published `1.3.0-pekko-1.1.x` with the latest dependencies.

**Comment by mayur9991** [comment]
@samueleresca Thanks 👍🏻
