### ISSUE TITLE
Latest library releases not available in Maven

### ISSUE THREAD

**Issue by LewisMitchell** [samueleresca/pekko-quartz-scheduler#93]
Looking in [Sonatype](https://s01.oss.sonatype.org/#nexus-search;quick~pekko-quartz-scheduler), it appears that [1.2.2-pekko-1.0.x](https://github.com/samueleresca/pekko-quartz-scheduler/releases/tag/1.2.2-pekko-1.0.x) and [1.3.0-pekko-1.1.x](https://github.com/samueleresca/pekko-quartz-scheduler/releases/tag/1.3.0-pekko-1.1.x) are not available as Scala 3 libraries.

Could these be published to Maven, please?

**Comment by samueleresca** [comment]
Sorry for the delay, these have been published.
